# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('test_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MatrixTestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.TextField()),
                ('matrix', models.TextField(default='[]')),
                ('matrix_size', models.IntegerField(default=1)),
            ],
        ),
    ]
