# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_freqrelationtestitem_relationtestitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codetestitem',
            old_name='depth_code',
            new_name='source_depth',
        ),
        migrations.AddField(
            model_name='codetestitem',
            name='test_depth',
            field=models.IntegerField(default=0),
        ),
    ]
