# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161015_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('source_depth', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.TextField()),
                ('test_depth', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='codetestitem',
            name='source_depth',
        ),
        migrations.RemoveField(
            model_name='codetestitem',
            name='test_depth',
        ),
        migrations.AlterField(
            model_name='codetestitem',
            name='source_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CodeItem'),
        ),
        migrations.AlterField(
            model_name='codetestitem',
            name='test_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TestItem'),
        ),
    ]
