# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_processedline'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeitem',
            name='body_length',
            field=models.IntegerField(default=0),
        ),
    ]
