---

- name: Check if nginx exists
  stat: path=/usr/sbin/nginx
  register: nginx_exists

- name: Add NGINX signing key
  become: yes
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  when: nginx_exists.stat.exists == False

- name: Add sources.list deb url for NGINX
  become: yes
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
  when: nginx_exists.stat.exists == False

- name: Install NGINX
  become: yes
  apt: name=nginx update_cache=yes state=latest cache_valid_time=86400
  tags: packages
  when: nginx_exists.stat.exists == False

- name: Ensure conf.d/default.conf is absent
  become: yes
  file: path=/etc/nginx/conf.d/default.conf  state=absent

- name: Ensure sites-available/default is absent
  become: yes
  file: path=/etc/nginx/sites-available/default  state=absent

- name: Ensure vagrant app configuration file
  become: Yes
  template: src=vagrant.app.conf.j2
            dest=/etc/nginx/conf.d/{{ app_name }}.conf
  notify: reload nginx
  when: vagrant_mode == 1

- name: Ensure staging app configuration file
  become: Yes
  template: src=staging.app.conf.j2
            dest=/etc/nginx/conf.d/{{ app_name }}.conf
  notify: reload nginx
  when: staging_mode == 1
  tags:
    - deploy

